services:

  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres124
      DB_NAME: chat_app_db
      REDIS_HOST: redis
      REDIS_PASSWORD: redis_password_123
      JWT_SECRET: change_me_in_production
      PORT: 3000
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres124
      POSTGRES_DB: chat_app_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5051:80"
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

volumes:
  postgres_data:
