CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(255) UNIQUE,
 password VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
 id INT AUTO_INCREMENT PRIMARY KEY,
 room_id INT,
 sender_id INT,
 message TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (room_id) REFERENCES rooms(id),
 FOREIGN KEY (sender_id) REFERENCES users(id)
);